"""Sphinx configuration.

The guide pages are Markdown (MyST); the API reference under ``api/`` is
generated by autodoc from the package docstrings, which are written in
Sphinx's rST style — that is why the ``:class:`` / ``:mod:`` roles in the
source cross-link for free. Build with ``uv run sphinx-build -W docs docs/_build/html``.
"""

from importlib.metadata import version as _version

project = "zenode"
author = "Fabian Bahr"
copyright = "2026, Hochschule Esslingen"
release = _version("zenode")
version = release

extensions = [
    "myst_parser",
    "sphinx.ext.autodoc",
    "sphinx.ext.napoleon",  # docstrings use Google-style Args:/Returns: sections
    "sphinx.ext.intersphinx",
    "sphinx_copybutton",
    "sphinxcontrib.mermaid",
]

# Guide pages link across files with GitHub-style anchors
# (e.g. contracts.md#quality-of-service); this makes MyST generate them.
myst_heading_anchors = 3
myst_enable_extensions = ["colon_fence", "deflist"]
# ```mermaid fences in the guides become mermaid directives instead of
# (unhighlightable) code blocks.
myst_fence_as_directive = ["mermaid"]

autodoc_member_order = "bysource"
autodoc_preserve_defaults = True
autodoc_default_options = {
    "members": True,
    "show-inheritance": True,
}

intersphinx_mapping = {
    "python": ("https://docs.python.org/3", None),
    "pydantic": ("https://docs.pydantic.dev/latest", None),
}

templates_path = []
exclude_patterns = ["_build"]

html_theme = "furo"
html_title = f"zenode {release}"
html_theme_options = {
    "source_repository": "https://github.com/hse-deb-algo-athlets/zenode",
    "source_branch": "main",
    "source_directory": "docs/",
}

# Strip prompts when copying shell blocks.
copybutton_prompt_text = r">>> |\.\.\. |\$ "
copybutton_prompt_is_regexp = True
